"""problem_centric_room_redesign

Revision ID: fabfb9e774e5
Revises: 
Create Date: 2026-05-29 14:58:53.156113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fabfb9e774e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('problem_statement', sa.Text(), nullable=False, server_default='No problem statement provided.'))
    # Remove server default after adding it to existing rows
    op.execute("ALTER TABLE rooms ALTER COLUMN problem_statement DROP DEFAULT")
    
    op.add_column('rooms', sa.Column('context', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('rooms', sa.Column('is_active', sa.Boolean(), nullable=True, server_default='true'))
    # Remove server default for is_active as well
    op.execute("ALTER TABLE rooms ALTER COLUMN is_active DROP DEFAULT")
    
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'is_active')
    op.drop_column('rooms', 'tags')
    op.drop_column('rooms', 'context')
    op.drop_column('rooms', 'problem_statement')
    # ### end Alembic commands ###
